version: '3.8'

services:
  tagger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80

volumes:
  sqlite_data: